<Project>
  <PropertyGroup>
    <VftTargetFramework>net10.0</VftTargetFramework>
    <VftTargetPlatformMinVersion>10.0.17763.0</VftTargetPlatformMinVersion>
    <AssemblyVersion>6.0.0.0</AssemblyVersion>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>x86;x64;arm64;AnyCPU</Platforms>
  </PropertyGroup>
</Project>
