<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <NoWarn>$(NoWarn);NU1507</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Avalonia" Version="11.3.11" />
    <PackageVersion Include="Avalonia.Desktop" Version="11.3.11" />
    <PackageVersion Include="Avalonia.Diagnostics" Version="11.3.11" />
    <PackageVersion Include="Avalonia.Themes.Fluent" Version="11.3.11" />
    <PackageVersion Include="AvaloniaUI.DiagnosticsSupport" Version="2.1.1" />
    <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageVersion Include="FluentAvaloniaUI" Version="2.4.1" />
    <PackageVersion Include="Gameloop.Vdf" Version="0.6.2" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.1" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.1" />
    <PackageVersion Include="Microsoft.ICU.ICU4C.Runtime" Version="68.2.0.9" />
    <PackageVersion Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageVersion Include="ReactiveUI.Avalonia" Version="11.3.8" />
    <PackageVersion Include="Sentry" Version="6.0.0" />
    <PackageVersion Include="Sentry.Extensions.Logging" Version="6.0.0" />
    <PackageVersion Include="System.CommandLine" Version="2.0.1" />
    <PackageVersion Include="System.Net.Http" Version="4.3.4" />
    <PackageVersion Include="System.Private.Uri" Version="4.3.2" />
    <PackageVersion Include="System.Text.RegularExpressions" Version="4.3.1" />
  </ItemGroup>
</Project>