namespace VRCFaceTracking.Params.Lip
{
    // TODO Remove duplicate expressions post testing!
    public enum LipShape_v3
    {
        //None = -1,
        JawRight = 0, // +JawX
        JawLeft = 1, // -JawX
        JawForward = 2,
        JawOpen = 3,
        MouthApeShape = 4,
        MouthUpperRight = 5, // +MouthUpper
        MouthUpperLeft = 6, // -MouthUpper
        MouthLowerRight = 7, // +MouthLower
        MouthLowerLeft = 8, // -MouthLower
        MouthUpperOverturn = 9,
        MouthLowerOverturn = 10,
        MouthPout = 11,
        MouthSmileRight = 12, // +SmileSadRight
        MouthSmileLeft = 13, // +SmileSadLeft
        MouthSadRight = 14, // -SmileSadRight
        MouthSadLeft = 15, // -SmileSadLeft
        CheekPuffRight = 16,
        CheekPuffLeft = 17,
        CheekSuck = 18,
        MouthUpperUpRight = 19,
        MouthUpperUpLeft = 20,
        MouthLowerDownRight = 21,
        MouthLowerDownLeft = 22,
        MouthUpperInside = 23,
        MouthLowerInside = 24,
        MouthLowerOverlay = 25,
        TongueLongStep1 = 26,
        TongueLongStep2 = 32,
        TongueDown = 30, // -TongueY
        TongueUp = 29, // +TongueY
        TongueRight = 28, // +TongueX
        TongueLeft = 27, // -TongueX
        TongueRoll = 31,
        TongueUpLeftMorph = 34,
        TongueUpRightMorph = 33,
        TongueDownLeftMorph = 36,
        TongueDownRightMorph = 35,
        SRanipalMax = 36,
        Brow_Lowerer_L = 37,
        Brow_Lowerer_R = 38,
        Cheek_Raiser_L = 41,
        Cheek_Raiser_R = 42,
        Cheek_Suck_L = 43,
        Cheek_Suck_R = 43,
        Chin_Raiser_B = 44,
        Chin_Raiser_T = 45,
        Dimpler_L = 46,
        Dimpler_R = 47,
        Eyes_Closed_L = 48,
        Eyes_Closed_R = 49,
        Eyes_Look_Down_L = 50,
        Eyes_Look_Down_R = 51,
        Eyes_Look_Left_L = 52,
        Eyes_Look_Left_R = 53,
        Eyes_Look_Right_L = 54,
        Eyes_Look_Right_R = 55,
        Eyes_Look_Up_L = 56,
        Eyes_Look_Up_R = 57,
        Inner_Brow_Raiser_L = 58,
        Inner_Brow_Raiser_R = 59,
        Jaw_Drop = 60,
        Jaw_Sideways_Left = 61,
        Jaw_Sideways_Right = 62,
        Jaw_Thrust = 63,
        Lid_Tightener_L = 64,
        Lid_Tightener_R = 65,
        Lip_Corner_Depressor_L = 66,
        Lip_Corner_Depressor_R = 67,
        Lip_Corner_Puller_L = 68,
        Lip_Corner_Puller_R = 69,
        Lip_Funneler_LB = 70,
        Lip_Funneler_LT = 71,
        Lip_Funneler_RB = 72,
        Lip_Funneler_RT = 73,
        Lip_Pressor_L = 74,
        Lip_Pressor_R = 75,
        Lip_Pucker_L = 76,
        Lip_Pucker_R = 77,
        Lip_Stretcher_L = 78,
        Lip_Stretcher_R = 79,
        Lip_Suck_LB = 80,
        Lip_Suck_LT = 81,
        Lip_Suck_RB = 82,
        Lip_Suck_RT = 83,
        Lip_Tightener_L = 84,
        Lip_Tightener_R = 85,
        Lips_Toward = 86,
        Lower_Lip_Depressor_L = 87,
        Lower_Lip_Depressor_R = 88,
        Mouth_Left = 89,
        Mouth_Right = 90,
        Nose_Wrinkler_L = 91,
        Nose_Wrinkler_R = 92,
        Outer_Brow_Raiser_L = 93,
        Outer_Brow_Raiser_R = 94,
        Upper_Lid_Raiser_L = 95,
        Upper_Lid_Raiser_R = 96,
        Upper_Lip_Raiser_L = 97,
        Upper_Lip_Raiser_R = 98,
        Max = 99
    }
}
