//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VRCFaceTracking.Strings {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.1.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("VRCFaceTracking.Strings.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string AppDisplayName {
            get {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }
        
        public static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        public static string Shell_Main_Content {
            get {
                return ResourceManager.GetString("Shell_Main_Content", resourceCulture);
            }
        }
        
        public static string ListDetails_NoSelection_Text {
            get {
                return ResourceManager.GetString("ListDetails_NoSelection_Text", resourceCulture);
            }
        }
        
        public static string Shell_ListDetails_Content {
            get {
                return ResourceManager.GetString("Shell_ListDetails_Content", resourceCulture);
            }
        }
        
        public static string Settings_Personalization_Text {
            get {
                return ResourceManager.GetString("Settings_Personalization_Text", resourceCulture);
            }
        }
        
        public static string Settings_Theme_Text {
            get {
                return ResourceManager.GetString("Settings_Theme_Text", resourceCulture);
            }
        }
        
        public static string Settings_Theme_Light_Content {
            get {
                return ResourceManager.GetString("Settings_Theme_Light_Content", resourceCulture);
            }
        }
        
        public static string Settings_Theme_Dark_Content {
            get {
                return ResourceManager.GetString("Settings_Theme_Dark_Content", resourceCulture);
            }
        }
        
        public static string Settings_Theme_Default_Content {
            get {
                return ResourceManager.GetString("Settings_Theme_Default_Content", resourceCulture);
            }
        }
        
        public static string Settings_About_Text {
            get {
                return ResourceManager.GetString("Settings_About_Text", resourceCulture);
            }
        }
        
        public static string Settings_AboutDescription_Text {
            get {
                return ResourceManager.GetString("Settings_AboutDescription_Text", resourceCulture);
            }
        }
        
        public static string SettingsPage_PrivacyTermsLink_Content {
            get {
                return ResourceManager.GetString("SettingsPage_PrivacyTermsLink_Content", resourceCulture);
            }
        }
        
        public static string SettingsPage_PrivacyTermsLink_NavigateUri {
            get {
                return ResourceManager.GetString("SettingsPage_PrivacyTermsLink_NavigateUri", resourceCulture);
            }
        }
        
        public static string AppNotificationSamplePayload {
            get {
                return ResourceManager.GetString("AppNotificationSamplePayload", resourceCulture);
            }
        }
        
        public static string Shell_Output_Content {
            get {
                return ResourceManager.GetString("Shell_Output_Content", resourceCulture);
            }
        }
        
        public static string Shell_Parameters_Content {
            get {
                return ResourceManager.GetString("Shell_Parameters_Content", resourceCulture);
            }
        }
        
        public static string ModuleRegistry_NoSelection_Text {
            get {
                return ResourceManager.GetString("ModuleRegistry_NoSelection_Text", resourceCulture);
            }
        }
        
        public static string Shell_ModuleRegistry_Content {
            get {
                return ResourceManager.GetString("Shell_ModuleRegistry_Content", resourceCulture);
            }
        }
        
        public static string Shell_ModuleConfig_Content {
            get {
                return ResourceManager.GetString("Shell_ModuleConfig_Content", resourceCulture);
            }
        }
        
        public static string About_Text {
            get {
                return ResourceManager.GetString("About_Text", resourceCulture);
            }
        }
        
        public static string Appearance_Text {
            get {
                return ResourceManager.GetString("Appearance_Text", resourceCulture);
            }
        }
        
        public static string Author_Text {
            get {
                return ResourceManager.GetString("Author_Text", resourceCulture);
            }
        }
        
        public static string AvatarStatus_Text {
            get {
                return ResourceManager.GetString("AvatarStatus_Text", resourceCulture);
            }
        }
        
        public static string LocalTestAvatar_Text {
            get {
                return ResourceManager.GetString("LocalTestAvatar_Text", resourceCulture);
            }
        }
        
        public static string LocalTestAvatarTooltip_Content {
            get {
                return ResourceManager.GetString("LocalTestAvatarTooltip_Content", resourceCulture);
            }
        }
        
        public static string Copyright_Description {
            get {
                return ResourceManager.GetString("Copyright_Description", resourceCulture);
            }
        }
        
        public static string Credits_Description {
            get {
                return ResourceManager.GetString("Credits_Description", resourceCulture);
            }
        }
        
        public static string Dependencies_Header {
            get {
                return ResourceManager.GetString("Dependencies_Header", resourceCulture);
            }
        }
        
        public static string Description_Text {
            get {
                return ResourceManager.GetString("Description_Text", resourceCulture);
            }
        }
        
        public static string Disclaimer_Header {
            get {
                return ResourceManager.GetString("Disclaimer_Header", resourceCulture);
            }
        }
        
        public static string Downloads_Text {
            get {
                return ResourceManager.GetString("Downloads_Text", resourceCulture);
            }
        }
        
        public static string EyeTrackingActive_Text {
            get {
                return ResourceManager.GetString("EyeTrackingActive_Text", resourceCulture);
            }
        }
        
        public static string FaceTrackingActive_Text {
            get {
                return ResourceManager.GetString("FaceTrackingActive_Text", resourceCulture);
            }
        }
        
        public static string EyeTrackingInactive_Text {
            get {
                return ResourceManager.GetString("EyeTrackingInactive_Text", resourceCulture);
            }
        }
        
        public static string FaceTrackingInactive_Text {
            get {
                return ResourceManager.GetString("FaceTrackingInactive_Text", resourceCulture);
            }
        }
        
        public static string BugRequestCard_Header {
            get {
                return ResourceManager.GetString("BugRequestCard_Header", resourceCulture);
            }
        }
        
        public static string PrivacyPolicyCard_Header {
            get {
                return ResourceManager.GetString("PrivacyPolicyCard_Header", resourceCulture);
            }
        }
        
        public static string LastUpdated_Text {
            get {
                return ResourceManager.GetString("LastUpdated_Text", resourceCulture);
            }
        }
        
        public static string LegacyParameters_Text {
            get {
                return ResourceManager.GetString("LegacyParameters_Text", resourceCulture);
            }
        }
        
        public static string Listening_on_Port_Text {
            get {
                return ResourceManager.GetString("Listening_on_Port_Text", resourceCulture);
            }
        }
        
        public static string ModulePage_Text {
            get {
                return ResourceManager.GetString("ModulePage_Text", resourceCulture);
            }
        }
        
        public static string msIncoming_Text {
            get {
                return ResourceManager.GetString("msIncoming_Text", resourceCulture);
            }
        }
        
        public static string msOutgoing_Text {
            get {
                return ResourceManager.GetString("msOutgoing_Text", resourceCulture);
            }
        }
        
        public static string no_modules_installed_warning_Title {
            get {
                return ResourceManager.GetString("no_modules_installed_warning_Title", resourceCulture);
            }
        }
        
        public static string no_modules_installed_warning_ButtonText {
            get {
                return ResourceManager.GetString("no_modules_installed_warning_ButtonText", resourceCulture);
            }
        }
        
        public static string osc_was_disabled_warning_Title {
            get {
                return ResourceManager.GetString("osc_was_disabled_warning_Title", resourceCulture);
            }
        }
        
        public static string osc_was_disabled_warning_Description {
            get {
                return ResourceManager.GetString("osc_was_disabled_warning_Description", resourceCulture);
            }
        }
        
        public static string OSCStatus_Text {
            get {
                return ResourceManager.GetString("OSCStatus_Text", resourceCulture);
            }
        }
        
        public static string Parameters_Text {
            get {
                return ResourceManager.GetString("Parameters_Text", resourceCulture);
            }
        }
        
        public static string Rating_Text {
            get {
                return ResourceManager.GetString("Rating_Text", resourceCulture);
            }
        }
        
        public static string ThemeSettings_Header {
            get {
                return ResourceManager.GetString("ThemeSettings_Header", resourceCulture);
            }
        }
        
        public static string ThemeSettings_Description {
            get {
                return ResourceManager.GetString("ThemeSettings_Description", resourceCulture);
            }
        }
        
        public static string Sending_on_Port_Text {
            get {
                return ResourceManager.GetString("Sending_on_Port_Text", resourceCulture);
            }
        }
        
        public static string ToggleTracking_Content {
            get {
                return ResourceManager.GetString("ToggleTracking_Content", resourceCulture);
            }
        }
        
        public static string CloneRepoCard_Header {
            get {
                return ResourceManager.GetString("CloneRepoCard_Header", resourceCulture);
            }
        }
        
        public static string OpenLocalStorageCard_Header {
            get {
                return ResourceManager.GetString("OpenLocalStorageCard_Header", resourceCulture);
            }
        }
        
        public static string UsageInstructions_Text {
            get {
                return ResourceManager.GetString("UsageInstructions_Text", resourceCulture);
            }
        }
        
        public static string Version_Text {
            get {
                return ResourceManager.GetString("Version_Text", resourceCulture);
            }
        }
        
        public static string OscSettings_Header {
            get {
                return ResourceManager.GetString("OscSettings_Header", resourceCulture);
            }
        }
        
        public static string OscSettings_Description {
            get {
                return ResourceManager.GetString("OscSettings_Description", resourceCulture);
            }
        }
        
        public static string no_modules_installed_warning_Description {
            get {
                return ResourceManager.GetString("no_modules_installed_warning_Description", resourceCulture);
            }
        }
        
        public static string CalibrationSettings_Header {
            get {
                return ResourceManager.GetString("CalibrationSettings_Header", resourceCulture);
            }
        }
        
        public static string CalibrationSettings_Description {
            get {
                return ResourceManager.GetString("CalibrationSettings_Description", resourceCulture);
            }
        }
        
        public static string RiskySettings_Header {
            get {
                return ResourceManager.GetString("RiskySettings_Header", resourceCulture);
            }
        }
        
        public static string RiskySettings_Description {
            get {
                return ResourceManager.GetString("RiskySettings_Description", resourceCulture);
            }
        }
        
        public static string AutoStartSettings_Header {
            get {
                return ResourceManager.GetString("AutoStartSettings_Header", resourceCulture);
            }
        }
        
        public static string AutoStartSettings_Description {
            get {
                return ResourceManager.GetString("AutoStartSettings_Description", resourceCulture);
            }
        }
        
        public static string CalibrationEnabledToggle_Header {
            get {
                return ResourceManager.GetString("CalibrationEnabledToggle_Header", resourceCulture);
            }
        }
        
        public static string CalibrationEnabledToggle_Description {
            get {
                return ResourceManager.GetString("CalibrationEnabledToggle_Description", resourceCulture);
            }
        }
        
        public static string ContCalibrationToggle_Header {
            get {
                return ResourceManager.GetString("ContCalibrationToggle_Header", resourceCulture);
            }
        }
        
        public static string ContCalibrationToggle_Description {
            get {
                return ResourceManager.GetString("ContCalibrationToggle_Description", resourceCulture);
            }
        }
        
        public static string TrackingCalibrateButton_Header {
            get {
                return ResourceManager.GetString("TrackingCalibrateButton_Header", resourceCulture);
            }
        }
        
        public static string TrackingCalibrateButton_Description {
            get {
                return ResourceManager.GetString("TrackingCalibrateButton_Description", resourceCulture);
            }
        }
        
        public static string CalibrationInfluenceSlider_Header {
            get {
                return ResourceManager.GetString("CalibrationInfluenceSlider_Header", resourceCulture);
            }
        }
        
        public static string CalibrationInfluenceSlider_Description {
            get {
                return ResourceManager.GetString("CalibrationInfluenceSlider_Description", resourceCulture);
            }
        }
        
        public static string CalibrateButton_Content {
            get {
                return ResourceManager.GetString("CalibrateButton_Content", resourceCulture);
            }
        }
        
        public static string ForceReInitButton_Description {
            get {
                return ResourceManager.GetString("ForceReInitButton_Description", resourceCulture);
            }
        }
        
        public static string ForceReInitButton_Header {
            get {
                return ResourceManager.GetString("ForceReInitButton_Header", resourceCulture);
            }
        }
        
        public static string ForceRelevancyToggle_Description {
            get {
                return ResourceManager.GetString("ForceRelevancyToggle_Description", resourceCulture);
            }
        }
        
        public static string ForceRelevancyToggle_Header {
            get {
                return ResourceManager.GetString("ForceRelevancyToggle_Header", resourceCulture);
            }
        }
        
        public static string ReInitButton_Content {
            get {
                return ResourceManager.GetString("ReInitButton_Content", resourceCulture);
            }
        }
        
        public static string ResetAvatarConfButton_Description {
            get {
                return ResourceManager.GetString("ResetAvatarConfButton_Description", resourceCulture);
            }
        }
        
        public static string ResetAvatarConfButton_Header {
            get {
                return ResourceManager.GetString("ResetAvatarConfButton_Header", resourceCulture);
            }
        }
        
        public static string ResetButton_Content {
            get {
                return ResourceManager.GetString("ResetButton_Content", resourceCulture);
            }
        }
        
        public static string ResetVRCFTButton_Description {
            get {
                return ResourceManager.GetString("ResetVRCFTButton_Description", resourceCulture);
            }
        }
        
        public static string ResetVRCFTButton_Header {
            get {
                return ResourceManager.GetString("ResetVRCFTButton_Header", resourceCulture);
            }
        }
        
        public static string HardwareDebug_Header {
            get {
                return ResourceManager.GetString("HardwareDebug_Header", resourceCulture);
            }
        }
        
        public static string HardwareDebug_Description {
            get {
                return ResourceManager.GetString("HardwareDebug_Description", resourceCulture);
            }
        }
        
        public static string Shell_TrackingSettings_Content {
            get {
                return ResourceManager.GetString("Shell_TrackingSettings_Content", resourceCulture);
            }
        }
        
        public static string ModuleConfig_Description_Text {
            get {
                return ResourceManager.GetString("ModuleConfig_Description_Text", resourceCulture);
            }
        }
        
        public static string ModuleConfig_Eye_Text {
            get {
                return ResourceManager.GetString("ModuleConfig_Eye_Text", resourceCulture);
            }
        }
        
        public static string ModuleConfig_Expression_Text {
            get {
                return ResourceManager.GetString("ModuleConfig_Expression_Text", resourceCulture);
            }
        }
        
        public static string ModuleConfig_Reload_Button {
            get {
                return ResourceManager.GetString("ModuleConfig_Reload_Button", resourceCulture);
            }
        }
        
        public static string ModuleConfig_PendingChanges_Text {
            get {
                return ResourceManager.GetString("ModuleConfig_PendingChanges_Text", resourceCulture);
            }
        }
        
        public static string ModuleConfig_PendingChanges_Tooltip {
            get {
                return ResourceManager.GetString("ModuleConfig_PendingChanges_Tooltip", resourceCulture);
            }
        }
    }
}
